#!/bin/python3
# https://www.hackerrank.com/challenges/one-week-preparation-kit-recursive-digit-sum/problem
import os
import random
import re
import sys

#
# Complete the 'superDigit' function below.
#
# The function is expected to return an INTEGER.
# The function accepts following parameters:
#  1. STRING n
#  2. INTEGER k
#

def superDigit(n, k):
    theSum = k * sum([int(digit) for digit in str(n)])
    while theSum > 10:
        theSum = sum([int(digit) for digit in str(theSum)])
    return theSum

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    first_multiple_input = input().rstrip().split()

    n = first_multiple_input[0]

    k = int(first_multiple_input[1])

    result = superDigit(n, k)

    fptr.write(str(result) + '\n')

    fptr.close()
